from django.urls import path

from bongusto.modules.auth import views as auth_views
from bongusto.modules.bitacora import views as bitacora_views
from bongusto.modules.calificaciones import views as calificaciones_views
from bongusto.modules.categorias import views as categorias_views
from bongusto.modules.chat import views as chat_views
from bongusto.modules.dashboard import views as dashboard_views
from bongusto.modules.eventos import views as eventos_views
from bongusto.modules.menus import views as menus_views
from bongusto.modules.musica import views as musica_views
from bongusto.modules.pedidos import views as pedidos_views
from bongusto.modules.perfil import views as perfil_views
from bongusto.modules.permisos import views as permisos_views
from bongusto.modules.productos import views as productos_views
from bongusto.modules.roles import views as roles_views
from bongusto.modules.shared import views as shared_views
from bongusto.modules.usuarios import views as usuarios_views

urlpatterns = [
    path("", auth_views.redirect_root),
    path("login", auth_views.login_view, name="login"),
    path("logout", auth_views.logout_view, name="logout"),
    path("healthz", shared_views.healthcheck, name="healthcheck"),
    path("api/mesas", shared_views.api_mesas, name="api_mesas"),
    path("api/mesas/", shared_views.api_mesas),
    path("api/mesas/asignar", shared_views.api_asignar_mesa, name="api_mesas_asignar"),
    path("api/mesas/asignar/", shared_views.api_asignar_mesa),
    path("api/mesas/<int:mesa_id>/estado", shared_views.api_actualizar_mesa, name="api_mesa_actualizar_estado"),
    path("api/mesas/<int:mesa_id>/estado/", shared_views.api_actualizar_mesa),
    path("api/mi-mesa", shared_views.api_mi_mesa, name="api_mi_mesa"),
    path("api/mi-mesa/", shared_views.api_mi_mesa),
    path("password/email", auth_views.password_email, name="password_email"),
    path("password/reset", auth_views.password_reset, name="password_reset"),
    path("dashboard", dashboard_views.index, name="dashboard"),
    path("dashboard/reporte", dashboard_views.reporte, name="dashboard_reporte"),
    path("perfil", perfil_views.ver, name="perfil"),
    path("perfil/editar", perfil_views.editar, name="perfil_editar"),
    path("perfil/actualizar", perfil_views.actualizar, name="perfil_actualizar"),
    path("usuarios", usuarios_views.index, name="usuarios"),
    path("usuarios/create", usuarios_views.create, name="usuario_create"),
    path("usuarios/<int:pk>", usuarios_views.ver, name="usuario_ver"),
    path("usuarios/store", usuarios_views.store, name="usuario_store"),
    path("usuarios/<int:pk>/edit", usuarios_views.edit, name="usuario_edit"),
    path("usuarios/<int:pk>/update", usuarios_views.update, name="usuario_update"),
    path("usuarios/<int:pk>/delete", usuarios_views.delete, name="usuario_delete"),
    path("usuarios/<int:pk>/toggle", usuarios_views.toggle_estado, name="usuario_toggle"),
    path("usuarios/reporte", usuarios_views.reporte, name="usuario_reporte"),
    path("roles", roles_views.index, name="roles"),
    path("roles/create", roles_views.create, name="rol_create"),
    path("roles/<int:pk>", roles_views.ver, name="rol_ver"),
    path("roles/store", roles_views.store, name="rol_store"),
    path("roles/<int:pk>/edit", roles_views.edit, name="rol_edit"),
    path("roles/<int:pk>/update", roles_views.update, name="rol_update"),
    path("roles/<int:pk>/delete", roles_views.delete, name="rol_delete"),
    path("permisos", permisos_views.index, name="permisos"),
    path("bitacora", bitacora_views.index, name="bitacora"),
    path("bitacora/create", bitacora_views.create, name="bitacora_create"),
    path("bitacora/<int:pk>", bitacora_views.ver, name="bitacora_ver"),
    path("bitacora/store", bitacora_views.store, name="bitacora_store"),
    path("bitacora/<int:pk>/edit", bitacora_views.edit, name="bitacora_edit"),
    path("bitacora/<int:pk>/update", bitacora_views.update, name="bitacora_update"),
    path("bitacora/<int:pk>/delete", bitacora_views.delete, name="bitacora_delete"),
    path("bitacora/reporte", bitacora_views.reporte, name="bitacora_reporte"),
    path("calificaciones", calificaciones_views.index, name="calificaciones"),
    path("calificaciones/<int:pk>", calificaciones_views.ver, name="calificacion_ver"),
    path("calificaciones/reporte", calificaciones_views.reporte, name="calificacion_reporte"),
    path("menus", menus_views.index, name="menus"),
    path("menus/create", menus_views.create, name="menu_create"),
    path("menus/<int:pk>", menus_views.ver, name="menu_ver"),
    path("menus/store", menus_views.store, name="menu_store"),
    path("menus/<int:pk>/edit", menus_views.edit, name="menu_edit"),
    path("menus/<int:pk>/update", menus_views.update, name="menu_update"),
    path("menus/<int:pk>/delete", menus_views.delete, name="menu_delete"),
    path("menus/importar", menus_views.importar_excel, name="menu_importar_excel"),
    path("menus/pdf", menus_views.pdf, name="menu_pdf"),
    path("categorias", categorias_views.index, name="categorias"),
    path("categorias/create", categorias_views.create, name="categoria_create"),
    path("categorias/<int:pk>", categorias_views.ver, name="categoria_ver"),
    path("categorias/store", categorias_views.store, name="categoria_store"),
    path("categorias/<int:pk>/edit", categorias_views.edit, name="categoria_edit"),
    path("categorias/<int:pk>/update", categorias_views.update, name="categoria_update"),
    path("categorias/<int:pk>/delete", categorias_views.delete, name="categoria_delete"),
    path("productos", productos_views.index, name="productos"),
    path("productos/create", productos_views.create, name="producto_create"),
    path("productos/<int:pk>", productos_views.ver, name="producto_ver"),
    path("productos/store", productos_views.store, name="producto_store"),
    path("productos/<int:pk>/edit", productos_views.edit, name="producto_edit"),
    path("productos/<int:pk>/update", productos_views.update, name="producto_update"),
    path("productos/<int:pk>/delete", productos_views.delete, name="producto_delete"),
    path("productos/importar", productos_views.importar_excel, name="producto_importar_excel"),
    path("productos/reporte", productos_views.reporte, name="producto_reporte"),
    path("musicas", musica_views.index, name="musicas"),
    path("musicas/nueva", musica_views.nueva, name="musica_nueva"),
    path("musicas/<int:pk>", musica_views.ver, name="musica_ver"),
    path("musicas/store", musica_views.store, name="musica_store"),
    path("musicas/<int:pk>/eliminar", musica_views.eliminar, name="musica_eliminar"),
    path("musicas/importar", musica_views.importar_excel, name="musica_importar_excel"),
    path("musicas/reporte", musica_views.reporte, name="musica_reporte"),
    path("api/musicas", musica_views.api_listar, name="api_musicas"),
    path("api/musicas/", musica_views.api_listar),
    path("api/musicas/cola", musica_views.api_cola, name="api_musicas_cola"),
    path("api/musicas/cola/", musica_views.api_cola),
    path("api/solicitudes-musica", musica_views.api_solicitar, name="api_solicitudes_musica"),
    path("api/solicitudes-musica/", musica_views.api_solicitar),
    path("eventos", eventos_views.index, name="eventos"),
    path("eventos/nuevo", eventos_views.nuevo, name="evento_nuevo"),
    path("eventos/<int:pk>", eventos_views.ver, name="evento_ver"),
    path("eventos/store", eventos_views.store, name="evento_store"),
    path("eventos/editar/<int:pk>", eventos_views.editar, name="evento_editar"),
    path("eventos/<int:pk>/update", eventos_views.update, name="evento_update"),
    path("eventos/<int:pk>/eliminar", eventos_views.eliminar, name="evento_eliminar"),
    path("eventos/pdf", eventos_views.pdf, name="evento_pdf"),
    path("api/clientes/login", usuarios_views.api_login_cliente, name="api_clientes_login"),
    path("api/clientes/login/", usuarios_views.api_login_cliente),
    path("api/meseros/login", usuarios_views.api_login_mesero, name="api_meseros_login"),
    path("api/meseros/login/", usuarios_views.api_login_mesero),
    path("api/clientes/register", usuarios_views.api_registro_cliente, name="api_clientes_register"),
    path("api/clientes/register/", usuarios_views.api_registro_cliente),
    path("api/session/refresh", usuarios_views.api_refresh_session, name="api_session_refresh"),
    path("api/session/refresh/", usuarios_views.api_refresh_session),
    path("api/calificaciones", calificaciones_views.api_crear, name="api_calificaciones"),
    path("api/calificaciones/", calificaciones_views.api_crear),
    path("api/menus", menus_views.api_listar, name="api_menus"),
    path("api/menus/", menus_views.api_listar),
    path("api/categorias", categorias_views.api_listar, name="api_categorias"),
    path("api/categorias/", categorias_views.api_listar),
    path("api/productos", productos_views.api_listar, name="api_productos"),
    path("api/productos/", productos_views.api_listar),
    path("api/pedidos", pedidos_views.listar_o_crear, name="api_pedidos"),
    path("api/pedidos/", pedidos_views.listar_o_crear),
    path("api/pedidos/<int:pk>", pedidos_views.detalle, name="api_pedido_detalle"),
    path("api/pedidos/<int:pk>/", pedidos_views.detalle),
    path("api/mesero/llamados", pedidos_views.llamados_mesero, name="api_llamados_mesero"),
    path("api/mesero/llamados/", pedidos_views.llamados_mesero),
    path("api/mesero/llamados/<int:pk>/atender", pedidos_views.atender_llamado, name="api_atender_llamado_mesero"),
    path("api/mesero/llamados/<int:pk>/atender/", pedidos_views.atender_llamado),
    path("api/chat/historial", chat_views.api_historial, name="api_chat_historial"),
    path("api/chat/historial/", chat_views.api_historial),
    path("api/chat/enviar", chat_views.api_enviar, name="api_chat_enviar"),
    path("api/chat/enviar/", chat_views.api_enviar),
    path("chat", chat_views.index, name="chat"),
]
